### ISSUE TITLE
Add shortcuts through graph

### ISSUE THREAD

**Issue by mvahowe** [mvahowe/proskomma-js#122]
- [x] mainBlocks (document)
- [x] mainText (document)
- [x] mainBlocksText (document)
- [x] mainBlocksTokens, mainBlocksItems (document)
- [x] blocksTokens, blocksItems, blocksText (sequence)
- [x] require id or (docSet plus bookCode) for top-level document (root)

**Comment by jdejoode** [comment]
What about letting docSets and documents default to all? So for instance, if you do `{ mainSequence { blocks { text } } }` you get the entire text of all the docSets? Just a thought

**Comment by jdejoode** [comment]
Some arguments could be implicit. So even blocks could be implicit (and be left out).

**Comment by jdejoode** [comment]
That's easy because we can tell a user: this shortcut is shorthand for X. And you can still link them back to the full query.

**Comment by mvahowe** [comment]
@jdejoode I like the `mainSequence` idea. I'm not sure about leaving out `blocks` because it's not the only root through the graph.

**Comment by mvahowe** [comment]
@jdejoode The problem with the `mainSequences` proposal is that you'd have no way to tell which sequence went with which docSet. (It's the 'you have to specify every field' thing.) The other endpoints work, although in some cases the output seems quite opaque, ie nested arrays with no labels to tell you which array is which.
