### ISSUE TITLE
Markdown Lexer

### ISSUE THREAD

**Issue by mvahowe** [mvahowe/proskomma-js#48]

**Comment by mvahowe** [comment]
@jag3773 Any information on the required flavor of Markdown, which markup you use, etc, would be useful. (There's no rush.)

**Comment by jag3773** [comment]
@mvahowe That's a difficult question to answer as there are so many. @klappy I wonder if you could point Mark to the library we are now using for markdown-translatable if you think that would be sufficient.

**Comment by klappy** [comment]
Here's the functionality that we use as the basis of MD parsing bidi to html: https://github.com/unfoldingWord/markdown-translatable/blob/master/src/core/markdown-converter.ts

We use this same one in most of our apps and rcls for consistency.
